export interface NavItem {
  title: string;
  href: string;
  external?: boolean;
}

export const mainNav: NavItem[] = [
  { title: "होम", href: "/" },
  { title: "मध्यप्रदेश न्यूज़", href: "/category/madhya-pradesh" },
  { title: "देश", href: "/category/india" },
  { title: "शहर", href: "/category/cities" },
  { title: "विदेश", href: "/category/world" },
  { title: "क्रिकेट", href: "/category/cricket" },
  { title: "मनोरंजन", href: "/category/entertainment" },
  { title: "वीडियो", href: "/videos" },
  { title: "आस्था", href: "/astrology" },
];

export const footerNav = {
  categories: [
    { title: "मध्यप्रदेश न्यूज़", href: "/category/madhya-pradesh" },
    { title: "देश", href: "/category/india" },
    { title: "शहर", href: "/category/cities" },
    { title: "विदेश", href: "/category/world" },
    { title: "क्रिकेट", href: "/category/cricket" },
    { title: "मनोरंजन", href: "/category/entertainment" },
    { title: "लाइफस्टाइल", href: "/category/lifestyle" },
    { title: "आस्था", href: "/astrology" },
  ],
  features: [
    { title: "शॉर्ट्स", href: "/shorts" },
    { title: "वीडियो बुलेटिन", href: "/videos" },
    { title: "पॉडकास्ट", href: "/podcast" },
    { title: "राशिफल", href: "/astrology" },
  ],
  company: [
    { title: "हमारे बारे में", href: "/about" },
    { title: "संपर्क करें", href: "/contact" },
    { title: "गोपनीयता नीति", href: "/privacy" },
    { title: "नियम और शर्तें", href: "/terms" },
  ],
};

export const trendingTopics = [
  "नेशनल फैमिली हेल्थ सर्वे",
  "SIR",
  "डी के शिवकुमार",
  "वैभव सूर्यवंशी",
  "सिद्धारमैया",
  "RCB",
  "राज्यसभा चुनाव",
  "IPL 2026",
  "PM मोदी",
  "फ्राईडे रिलीज",
];

export const mpDistricts = [
  { title: "इंदौर", href: "/category/madhya-pradesh/indore" },
  { title: "उज्जैन", href: "/category/madhya-pradesh/ujjain" },
  { title: "ग्वालियर", href: "/category/madhya-pradesh/gwalior" },
  { title: "जबलपुर", href: "/category/madhya-pradesh/jabalpur" },
  { title: "भोपाल", href: "/category/madhya-pradesh/bhopal" },
  { title: "रीवा", href: "/category/madhya-pradesh/rewa" },
  { title: "सागर", href: "/category/madhya-pradesh/sagar" },
  { title: "सतना", href: "/category/madhya-pradesh/satna" },
  { title: "छतरपुर", href: "/category/madhya-pradesh/chhatarpur" },
  { title: "छिंदवाड़ा", href: "/category/madhya-pradesh/chhindwara" },
  { title: "रतलाम", href: "/category/madhya-pradesh/ratlam" },
  { title: "देवास", href: "/category/madhya-pradesh/dewas" },
  { title: "मुरैना", href: "/category/madhya-pradesh/morena" },
  { title: "भिंड", href: "/category/madhya-pradesh/bhind" },
  { title: "गुना", href: "/category/madhya-pradesh/guna" },
  { title: "शिवपुरी", href: "/category/madhya-pradesh/shivpuri" },
  { title: "विदिशा", href: "/category/madhya-pradesh/vidisha" },
  { title: "सीहोर", href: "/category/madhya-pradesh/sehore" },
  { title: "बैतूल", href: "/category/madhya-pradesh/betul" },
  { title: "खंडवा", href: "/category/madhya-pradesh/khandwa" },
  { title: "खरगोन", href: "/category/madhya-pradesh/khargone" },
  { title: "धार", href: "/category/madhya-pradesh/dhar" },
  { title: "झाबुआ", href: "/category/madhya-pradesh/jhabua" },
  { title: "अलीराजपुर", href: "/category/madhya-pradesh/alirajpur" },
  { title: "बड़वानी", href: "/category/madhya-pradesh/barwani" },
  { title: "बुरहानपुर", href: "/category/madhya-pradesh/burhanpur" },
  { title: "नीमच", href: "/category/madhya-pradesh/neemuch" },
  { title: "मंदसौर", href: "/category/madhya-pradesh/mandsaur" },
  { title: "शाजापुर", href: "/category/madhya-pradesh/shajapur" },
  { title: "आगर मालवा", href: "/category/madhya-pradesh/agar-malwa" },
  { title: "राजगढ़", href: "/category/madhya-pradesh/rajgarh" },
  { title: "रायसेन", href: "/category/madhya-pradesh/raisen" },
  { title: "हरदा", href: "/category/madhya-pradesh/harda" },
  { title: "नर्मदापुरम", href: "/category/madhya-pradesh/narmadapuram" },
  { title: "दमोह", href: "/category/madhya-pradesh/damoh" },
  { title: "पन्ना", href: "/category/madhya-pradesh/panna" },
  { title: "टीकमगढ़", href: "/category/madhya-pradesh/tikamgarh" },
  { title: "निवाड़ी", href: "/category/madhya-pradesh/niwari" },
  { title: "अशोकनगर", href: "/category/madhya-pradesh/ashoknagar" },
  { title: "दतिया", href: "/category/madhya-pradesh/datia" },
  { title: "श्योपुर", href: "/category/madhya-pradesh/sheopur" },
  { title: "उमरिया", href: "/category/madhya-pradesh/umaria" },
  { title: "शहडोल", href: "/category/madhya-pradesh/shahdol" },
  { title: "अनूपपुर", href: "/category/madhya-pradesh/anuppur" },
  { title: "डिंडोरी", href: "/category/madhya-pradesh/dindori" },
  { title: "मंडला", href: "/category/madhya-pradesh/mandla" },
  { title: "बालाघाट", href: "/category/madhya-pradesh/balaghat" },
  { title: "सिवनी", href: "/category/madhya-pradesh/seoni" },
  { title: "नरसिंहपुर", href: "/category/madhya-pradesh/narsinghpur" },
  { title: "कटनी", href: "/category/madhya-pradesh/katni" },
  { title: "सीधी", href: "/category/madhya-pradesh/sidhi" },
  { title: "सिंगरौली", href: "/category/madhya-pradesh/singrauli" },
  { title: "मऊगंज", href: "/category/madhya-pradesh/mauganj" },
  { title: "पांढुर्णा", href: "/category/madhya-pradesh/pandhurna" },
  { title: "मैहर", href: "/category/madhya-pradesh/maihar" },
].sort((a, b) => a.title.localeCompare(b.title, 'hi'));
